one = export blah="I was set!"; echo $$blah

define two
export blah="I was set!"
echo $$blah
endef

foo := $(if this-is-not-empty,then!,else!)
empty :=
bar := $(if $(empty),then!,else!)

all: 
	@echo "This prints 'I was set'"
	@$(one)
	@echo "This does not print 'I was set' because each command runs in a separate shell"
	@$(two)
	@echo $(foo)
	@echo $(bar)
