# Items are created using their add_*** commands.

# All items must have a tag which can either be specified or are automatically generated by DPG.

# Tags can be either integers or strings and are used to refer to the item after it has been created.

# Items return their tag when they are created.

import dearpygui.dearpygui as dpg

def create_item():
    with dpg.window(tag="Primary Window",label="Tutorial"):
        b0 = dpg.add_button(label="button 0")
        b1 = dpg.add_button(tag=100, label="Button 1")
        dpg.add_button(tag="Btn2", label="Button 2")

    print(b0)
    print(b1)
    print(dpg.get_item_label("Btn2"))

    dpg.create_viewport(title='Custom Title', width=600, height=200)
    dpg.setup_dearpygui()
    dpg.show_viewport()
    dpg.set_primary_window("Primary Window", True)
    dpg.start_dearpygui()

def create_container():
    with dpg.window(label="Tutorial"):
        dpg.add_button(label="Button 1")
        dpg.add_button(label="Button 2")
        with dpg.group():
            dpg.add_button(label="Button 3")
            dpg.add_button(label="Button 4")
            with dpg.group() as group1:
                pass
    dpg.add_button(label="Button 6", parent=group1)
    dpg.add_button(label="Button 5", parent=group1)

    dpg.create_viewport(title='Custom Title', width=600, height=400)
    dpg.setup_dearpygui()
    dpg.show_viewport()
    dpg.start_dearpygui()

if __name__ == '__main__':
    dpg.create_context()
    # create_item()
    create_container()
    dpg.destroy_context()
